// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5dEqyO1Qc1cdoiamVshu8mQwvU2oD0qI',
    appId: '1:169505452955:web:7505bd0e2cad5006b0273e',
    messagingSenderId: '169505452955',
    projectId: 'angazafb1',
    authDomain: 'angazafb1.firebaseapp.com',
    storageBucket: 'angazafb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5QsHZ32juKRwqmDB7XsSWyujHQd1TYI',
    appId: '1:169505452955:android:d5c0a3a30bd684f0b0273e',
    messagingSenderId: '169505452955',
    projectId: 'angazafb1',
    storageBucket: 'angazafb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXOopQCSughVlKD2BuWAUVViJurhN73U',
    appId: '1:169505452955:ios:4d2734bf567912abb0273e',
    messagingSenderId: '169505452955',
    projectId: 'angazafb1',
    storageBucket: 'angazafb1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXOopQCSughVlKD2BuWAUVViJurhN73U',
    appId: '1:169505452955:ios:4d2734bf567912abb0273e',
    messagingSenderId: '169505452955',
    projectId: 'angazafb1',
    storageBucket: 'angazafb1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5dEqyO1Qc1cdoiamVshu8mQwvU2oD0qI',
    appId: '1:169505452955:web:ebba2df73456b367b0273e',
    messagingSenderId: '169505452955',
    projectId: 'angazafb1',
    authDomain: 'angazafb1.firebaseapp.com',
    storageBucket: 'angazafb1.firebasestorage.app',
  );

}