name: Flutter CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: 'stable' }
      - run: flutter pub get
        working-directory: mobile
      - run: flutter analyze
        working-directory: mobile
      - run: flutter test
        working-directory: mobile
